version: '3.0'

services:
    django:
        network_mode: "host"
        build:
            context: backend
        container_name: dev_sampleproject_dj01
        command: bash -c 'python manage.py migrate && python manage.py collectstatic --noinput && gunicorn -b 0.0.0.0:8000 backend.wsgi:application'
        env_file: .env
        image: django-image-sampleproject
        volumes:
            - ./backend:/app
        ports:
            - "8000:8000"
    nuxt:
        build:
            context: frontend
        container_name: dev_sampleproject_nx01
        command: bash -c 'yarn build && yarn start'
        env_file: .env
        stdin_open: true
        tty: true
        volumes:
            - ./frontend:/app
            - exclude:/app/node_modules
        depends_on:
            - django
        ports:
            - "4444:3000"

volumes:
    exclude:
